#!/usr/bin/env bash
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

usage() {
    echo "Usage: optimize FILENAME"
}

getmimetype() {
    mimetype --output-format "%m" "$1"
}

checkoptimizerinstalled() {
    MIMETYPE=$1
    OPTIMIZER=$(which $2)
    if [ ! -x "$OPTIMIZER" ]; then
        echo "Please install $2 to optimize $1 files"
        exit 1
    fi
}

process() {
    INPUTFILE="$1"
    MIMETYPE=$(getmimetype "$INPUTFILE")
    case "$MIMETYPE" in
        "application/javascript")
            checkoptimizerinstalled $MIMETYPE yui-compressor
            TEMPFILE=$(tempfile)
            yui-compressor --nomunge "$INPUTFILE" -o $TEMPFILE
            mv $TEMPFILE "$INPUTFILE"
            ;;
        "image/gif")
            checkoptimizerinstalled $MIMETYPE gifsicle
            TEMPFILE=$(tempfile)
            gifsicle -O3 "$INPUTFILE" -o $TEMPFILE
            mv $TEMPFILE "$INPUTFILE"
            ;;
        "image/jpeg")
            checkoptimizerinstalled $MIMETYPE jpegoptim
            jpegoptim --strip-all "$INPUTFILE"
            ;;
        "image/png")
            checkoptimizerinstalled $MIMETYPE optipng
            optipng -o 7 "$INPUTFILE"
            checkoptimizerinstalled $MIMETYPE pngcrush
            pngcrush -reduce -brute -notfilecheck "$INPUTFILE" "$INPUTFILE"
            ;;
        "text/css")
            checkoptimizerinstalled $MIMETYPE yui-compressor
            TEMPFILE=$(tempfile)
            yui-compressor "$INPUTFILE" -o $TEMPFILE
            mv $TEMPFILE "$INPUTFILE"
            ;;
        *)
            echo "Mime-Type $MIMETYPE not supported."
            ;;
    esac
}

if [ "$#" == "0" ]; then
    usage
    exit 1
fi

INPUTFILE="$1"
if [ -z "$INPUTFILE" ]; then
    usage
    exit 1
fi

while (($#)); do
    if [ -f "$1" ]; then
        process "$1"
    elif [ -d "$1" ]; then
        for file in $(find $1 -type f); do
            process "$file"
        done
    else
        echo "ERROR: $1 is no file or directory."
        exit 1
    fi
    shift
done